/*
 * Automatically generated by make menuconfig: don't edit
 */
#define AUTOCONF_INCLUDED

/*
 * hal Configuration
 */
#define CFG_ARM_S3C2440 1
#undef  CFG_ARM_S3C2410
#undef  CFG_ARM_S3C44B0
#undef  CFG_ARM_LPC2131
#undef  CFG_ARM_LPC2200
#undef  CFG_ARM_PB11MPCORE
#undef  CFG_ARM_STM3210
#undef  CFG_X86_EMU_SINGLE
#undef  CFG_X86_EMU_CMP
#undef  CFG_BRD_TEMPLATE

/*
 * kernel configuration
 */
#define CFG_MEM_BUDDY 1
#undef  CFG_MEM_SLATE
#undef  CFG_MEM2
#undef  CFG_THRD_SLICE
#undef  CFG_THRD_PERIOD
#define CFG_MAX_THREAD (40)
#define CFG_MIN_STACK_SIZE (512)
#undef  CFG_PM
#undef  CFG_EVT_MBOX
#undef  CFG_EVT_SEM
#undef  CFG_MSG
#undef  CFG_SOFT_DELAY
#define CFG_TICKS_PER_SEC (100)
#undef  CFG_HOOK

/*
 * Driver configuration
 */
#undef  CFG_DRIVER

/*
 * Bsp configuration
 */

/*
 * Test configuration
 */
#undef  CFG_TEST

/*
 * System hacking
 */
#define CFG_BAUD_RATE (38400)
#undef  CFG_OUT_SEMI
#undef  CFG_DEBUG
#undef  CFG_STAT
#define __GNU_C__ 1
