/*
 * Automatically generated by make menuconfig: don't edit
 */
#define AUTOCONF_INCLUDED

/*
 * kernel configuration
 */
#define CFG_MEM2 1
#define CFG_MEM2_SIZE (1024000)
#define CFG_THRD_PERIOD 1
#define CFG_HARD_RT_PRIO_NUM (0)
#define CFG_MAX_THREAD (40)
#define CFG_MIN_STACK_SIZE (1024)
#define CFG_EVT_MBOX 1
#define CFG_EVT_SEM 1
#define CFG_MSG 1
#define CFG_SOFT_DELAY 1
#define CFG_TICKS_PER_SEC (100)

/*
 * Driver configuration
 */
#define CFG_DRIVER 1
#define CFG_DRV_NET_DM9000 1

/*
 * Plugin configuration
 */
#define CFG_PLUGIN_NET 1

/*
 * User configuration
 */
#define CFG_SHELL 1

/*
 * System hacking
 */
#define CFG_BAUD_RATE (115200)
#define CFG_DEBUG 1
